NAME: alaeset
DATASET:
  PART_COUNT: 16
  SIZE: 48000
  FFHQ_SOURCE: /home/hans/trainsets/alaeset/r%02d.tfrecords
  PATH: /home/hans/trainsets/alaeset/r%02d.tfrecords.%03d
  MAX_RESOLUTION_LEVEL: 7
  SAMPLES_PATH: /home/hans/neurout/alaeset/samples
  STYLE_MIX_PATH: /home/hans/neurout/alaeset/style_mixing
MODEL:
  LATENT_SPACE_SIZE: 512
  LAYER_COUNT: 7
  MAX_CHANNEL_COUNT: 512
  START_CHANNEL_COUNT: 32
  DLATENT_AVG_BETA: 0.995
  MAPPING_LAYERS: 8
OUTPUT_DIR: /home/hans/neurout/alaeset/training
TRAIN:
  BASE_LEARNING_RATE: 0.002
  EPOCHS_PER_LOD: 2
  LEARNING_DECAY_RATE: 0.1
  LEARNING_DECAY_STEPS: []
  TRAIN_EPOCHS: 112
  #                  4     8       16      32       64      128     256
  LOD_2_BATCH_2GPU: [512,  256,    128,    64,      32,     32,     16]
  LEARNING_RATES: [0.0015, 0.0015, 0.0015, 0.0015,  0.0015, 0.0015, 0.002]
 